This notebook shows how to read the wordcount data directly from the mysql binary file. This is likely to be the fastest possible way to iterate over the whole thing. It will only work on Bookworms created under certain, undefined processor architectures. Probably anything you're likely to build, though, will work. We're not talking about Mac vs. Linux type differences, but things like default endianness in the processor.

First we define the source. This is already a sign things are pretty out of hand.

In [218]:
source = "/drobo/mysql/hathipd"

In [621]:
import numpy as np
import sys
class BinaryBookworm():
    def __init__(self,source_dir):
        #self.file = open(source + "/master_bookcounts.MYD","rb")
        self.memmap = np.memmap(source + "/master_bookcounts.MYD","<i1")
        self.i = 0
    def __iter__(self):
        return self
    def next(self):
        zero = np.zeros(4*3*nrows,'<i1')
        zero[[0,1,2,4,5,6,8,9,10]] = f[range(self.i + 1,self.i + 10)]
        self.i += 10
        return zero.view('<i4')
    def old_next(self):
        line = self.file.read(10)
        if len(line)==0:
            raise StopIteration
        if line[9] != "\x00" or line[0] != "\xff":
            if (np.fromstring(line [9],'<i1') <= 2):
                # MySQL documentation says the end of a record is always null, but about 5 per million seem
                # to me to be one or two. I wonder if these are errors from the load data infile or something?
                return self.next()
            construit = line[1:4] + "\x00" + line[4:7] + "\x00" + line[7:10] + "\x00"
            sys.stderr.write("unparseable\n")
            # Three ways of writing any errors that look bad.
            sys.stderr.write("\t" + line.encode("hex") + "\n")
            sys.stderr.write("\t" + str(np.fromstring(line,"<i1")) + "\n")
            sys.stderr.write("\t" + str(np.fromstring(construit,"<i4")) + "\n")
        construit = line[1:4] + "\x00" + line[4:7] + "\x00" + line[7:10] + "\x00"
        return np.fromstring(construit,"<i4")
reading = BinaryBookworm(source)

In [752]:


print reading.i/10/1000000
reading.i += 1000000000
reading.next()

253


array([556483,  53421,      1], dtype=int32)

[295779   4986      6]


In [753]:
foo = []
i = 0
for line in reading:
    i+=1
    foo.append(line)
    if i > 1000000:
        break
print len(foo)

1000001


In [562]:
foo[:3]

[array([295779,   4986,      6], dtype=int32),
 array([295779, 187140,      1], dtype=int32),
 array([295779, 294054,      2], dtype=int32)]

In [184]:
while True:
    parse_row(readable)

StopIteration: 

In [98]:
read

In [100]:
a = np.ndarray(len(buf), np.dtype('>i1'), buf)
e = np.zeros(len(buf) / 6, np.dtype('>i4'))


In [104]:
for i in range(3):
    e.view(dtype='>i4')[i + 1::4] = \
     a.view(dtype='>i4')[i::3]


ValueError: new type not compatible with array.

In [113]:
foo[1:4]

'\x01\x00\x00'

In [112]:
a.data

<read-only buffer for 0x105397260, size 9, offset 0 at 0x10536fb70>